### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#15]
Hello, the current system on how the icons are retrieved is very bad unfortunately, most of the time the icons don’t show, or they display the latest icon, but only some work, the site would look much prettier with all the icons working, which the scraper should scrape the icons off the app, but most importantly, DO NOT REQUIRE ALL THE ARCHIVES TO BE SCRAPPED AGAIN. Instead use the icon data over here: https://github.com/stuffed18/ipa-archive-updated and use those icon caches when they get scrapped. Only future apps that do not include in that archive will be scraped.

**Comment by CatsLover2006** [comment]
Due to the way that the database works, it will require a full refresh of the database. Additionally, the reason so many of the apps have no icon is because I use a url present in the iTunesMetadata.plist to point to the icon. If the icon that url points to was updated, the icon is updated. A lot of the apps in the archive don’t have a iTunesMetadata.plist. Also, some of the broken icons are because of an SSL misconfiguration that’s on _Apple’s_ end.

**Comment by CatsLover2006** [comment]
Storing the icon for each app would take up too much space on my web server, as well.

**Comment by CatsLover2006** [comment]
I do plan to make another program where a custom url for app icons can be added to the database, but that will be a much later project.

**Comment by upintheairsheep** [comment]
> I do plan to make another program where a custom url for app icons can be added to the database, but that will be a much later project.

> Storing the icon for each app would take up too much space on my web server, as well.

I would say to do the custom URL program, plus not having it stored on your server (although I originally intended for it, it wasn’t a requirement), just find a way to scrape the metadata from the other project and have it link to the raw icons on stuffed18’s GitHub

**Comment by upintheairsheep** [comment]
But that requires the custom URL to be implemented, so it would take a bit of time before then.

**Comment by upintheairsheep** [comment]
Additionally, you can link to contents of ipa files in the IA, including images like icons.

**Comment by CatsLover2006** [comment]
This program assumes it can’t access the contents of IPA files via a url. The only real solution to the problem would be to slot a data URL into the database, but that would absolutely explode the database file size beyond what my server can handle. Also, any automated solution would require everything to be scanned again, which could take an astronomical amount of time.

**Comment by CatsLover2006** [comment]
And the custom URLs already exist in the database. In fact, one already exists on the main instance; Touch & Go, one of the apps from TouchHLE’s archive, didn't have an app icon. I manually went into the database, and fixed it with the app icon from TouchHLE’s website (as well as adding back the developer). The problem is that this can’t be automated without blowing up the file size.

**Comment by CatsLover2006** [comment]
Never mind, I looked into data URLs, and while having regular URLs is objectively better for storage and quality reasons, using a data for a JPEG isn’t that space heavy, especially since it’s a single data url for all versions of an app. So, I’ve implemented data URLs for when a regular web link is not available (although regular web links will always be preferred to save space)

**Comment by CatsLover2006** [comment]
Finally actually done, update is up, I’ll have to re-scan all the IPA files where the app didn’t already have an online icon (which is the lesser bit of them)

**Comment by CatsLover2006** [comment]
For some reason not all apps have icons, but this seems to be a bug within Java, and not anything I can do about. Some apps also just… don’t have an icon for whatever reason, even when installed.

**Comment by upintheairsheep** [comment]
> Finally actually done, update is up, I’ll have to re-scan all the IPA files where the app didn’t already have an online icon (which is the lesser bit of them)

For the ones that do use icons on the web, consider pointing them to https://github.com/stuffed18/ipa-archive-updated 's GH repo instead, due to Apple's SSL stuff and "modernization" (pointing to current icons).
