### ISSUE TITLE
Contemporary iOS support

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#17]
1. Consider making a contemporary iOS theme for modern iOS devices (different from early flat, compare the settings app of iOS 9 and 16), but even if you decline this, the search icon should be fixed.
2. On iOS 11 or higher, 32-bit apps should be hidden, only ARM64/ARMv8 apps should be displayed, but add a setting to show incompatible apps on modern iOS, removing all autofilters for the purpose of modern iOS users looking to check out classic apps.
3. Add support for Install with AltStore, Install with SideStore, and Install with TrollStore (hidden on legacy devices), TrollStore uses apple-magnifier://install?url=IPAURL, AltStore altstore://install?url=[download url] , and SideStore sidestore://install?url=[download url]
4. Add support for scraping AltStore repos, as shown in the previous issue

**Comment by CatsLover2006** [comment]
Since architecture listings are made available for users to look at, I don’t think that removing the apps from the listing will be all that helpful. Besides, with the current infrastructure, I wouldn’t be able to implement a singular client-side setting without having a full server rewrite. However, I do quite like the idea of installing with alternate stores; I’ll probably have those buttons show up on versions where that install method is supported (14.0-16.6.1 & 17.0 for Trollstore, 14.0+ for Sidestore, and 12.2+ for Altstore). Only thing is that, on iPads outside of the iPad mini, I wouldn’t be able to show these buttons, as they advertise themselves as Macs by default (and use the exact same user agent as a Mac running an equivalent version of macOS, which makes it impossible to tell what version of iOS the iPad is running)

**Comment by CatsLover2006** [comment]
Also, cytyle doesn’t exist for modern iOS, so it’d full server rewrite for a feature that most people wouldn’t notice.

**Comment by CatsLover2006** [comment]
I have now updated the search icon for iOS 7+, with the exact same conditions as with the style change, so the webapp will always be visually consistent with itself. Part 2 can’t be reasonably implemented, as previously mentioned, since adding a setting to the webapp would incur a full server rewrite, and anyone with knowledge of this webapp will know that ARMv7 apps don’t run on iOS 11 and above. As for parts 3 and 4, I’ll start on them tomorrow, it’s 2am and I need sleep.

**Comment by CatsLover2006** [comment]
Sorry about the lack of updates: here’s what’s been happening:

- TrollStore, AltStore, and SideStore links are added for versions where they could be present
- Modern iOS “theme” now uses the icon mask used in iOS 7 and newer, the mask technically applies to the search icon as well but it will never be visible due to the border radius
- changed placeholder app icon from the iOS 7+ placeholder app icon to the icon of the webapp

Planning to add Altstore repo parsing in the near future. I also plan to implement a TrollApps repo, #18

**Comment by CatsLover2006** [comment]
Closing as at this point the only remaining task is present in #16
