### ISSUE TITLE
Databasify it

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#4]
Hello, wouldn’t it be much better to just “databaseify” the links instead of making one huge list of links inside of an XML? Additionally can all scraped app metadata be inside of a database, including app icons (to not spam the internet archive with requests or overload your servers with downloading IPAs constantly).

**Comment by CatsLover2006** [comment]
Currently, all app metadata is in a JSON-based database. Icons are stored as whatever URL the app has in its metadata, which should never point to archive.org. 
In a nutshell, apps are stored in a list; due to the way Java works, this makes it really easy to do an absolute search on all elements really fast. Each app stores its name, its bundle ID, the earliest supported iOS version for any of its versions, its developer (alongside which app version it got that from), the icon URL (also alongside which app version it got that from), and a list of versions. Each version stores the lowest iOS version it supports, and a list of URLs for that version. All this information is sourced from two files in each IPA: `iTunesMetadata.plist`, and the app’s `info.plist`.
The XML files are what archive.org creates, so I can’t turn that into a database; archive.org generates them automatically, I just read it to see what IPA files exist. Before parsing a URL, I check the app metadata database to see if it’s already been parsed, both to reduce the number of requests and to save time.
The idea of storing app URLs to parse in a database is a good idea, although how I’d implement it is the question right now. I’ll probably just write an application to generate the file, and read it back in on the server. It would also be smart to also roll up the other configuration (port number, donation link, and host) into that file.

**Comment by CatsLover2006** [comment]
For context, on any running server, there will be a file called `db.json` alongside all the other assets used by the server. This is automatically generated as the server runs through each IPA file, and the server will save it every two minutes while it’s actively parsing IPA files. To save time and RAM on my own instance, I run the server on a local machine, and copy the database to the server when I want to update it. The only other files that need to be added as configuration are `host.txt`, which stores the domain the instance is hosted on to allow for iOS Direct Install, and `donate.txt`, an optional file which stores a link to a donation page. All of these are simple strings, and it would not be hard to roll all these up into a simple JSON file.

**Comment by CatsLover2006** [comment]
all configuration (including the archives and extra files to parse) are now stored in a file alongside the database called `config.json`. Closing as this is effectively complete

**Comment by upintheairsheep** [comment]
OK.
